# Generated by Django 3.1 on 2020-12-11 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="answer",
            old_name="answer",
            new_name="answer_body",
        ),
        migrations.AlterField(
            model_name="answer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="questions.question",
                verbose_name="سوال",
            ),
        ),
        migrations.AlterField(
            model_name="answer",
            name="status",
            field=models.CharField(
                choices=[("published", "انتشاریافته"), ("draft", "پیش نویس")],
                default="draft",
                max_length=12,
                null=True,
                verbose_name="وضعیت انتشار",
            ),
        ),
    ]
