# Generated by Django 3.1 on 2020-12-12 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0002_auto_20201211_1637"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(allow_unicode=True, null=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="slug",
            field=models.SlugField(allow_unicode=True, null=True),
        ),
    ]
