# Generated by Django 3.1 on 2020-12-12 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0003_auto_20201212_2054"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={"verbose_name": "برچسب", "verbose_name_plural": "برچسب ها"},
        ),
        migrations.AddField(
            model_name="question",
            name="question_tag",
            field=models.ManyToManyField(
                blank=True, to="questions.Tag", verbose_name="برچسب"
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="created_time",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="تاریخ ایجاد"
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="slug",
            field=models.SlugField(allow_unicode=True, null=True),
        ),
        migrations.AddField(
            model_name="tag",
            name="tag_name",
            field=models.CharField(blank=True, max_length=12, verbose_name="برچسب ها"),
        ),
        migrations.AddField(
            model_name="tag",
            name="updated_time",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="تاریخ به روزرسانی"
            ),
        ),
        migrations.RemoveField(
            model_name="question",
            name="question_category",
        ),
        migrations.AddField(
            model_name="question",
            name="question_category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="questions.category",
                verbose_name="دسته بندی سوال",
            ),
        ),
        migrations.AlterModelTable(
            name="tag",
            table="tags",
        ),
    ]
