# Generated by Django 3.1 on 2020-12-15 08:11

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0006_remove_tag_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="question_photo",
        ),
        migrations.AddField(
            model_name="question",
            name="answered",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="پاسخ داده شده "
            ),
        ),
        migrations.AlterField(
            model_name="answer",
            name="answer_body",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="پاسخ"),
        ),
        migrations.AlterField(
            model_name="answerreport",
            name="report_description",
            field=ckeditor.fields.RichTextField(
                blank=True, null=True, verbose_name="متن گزارش"
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_text",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="متن سوال"),
        ),
        migrations.AlterField(
            model_name="questionreport",
            name="report_description",
            field=ckeditor.fields.RichTextField(
                blank=True, null=True, verbose_name="متن گزارش"
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="created_time",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="تاریخ ایجاد"
            ),
        ),
    ]
