# Generated by Django 3.1 on 2020-12-07 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category_name",
                    models.CharField(
                        max_length=100, null=True, verbose_name="نام دسته بندی"
                    ),
                ),
                (
                    "created_time",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        null=True,
                        verbose_name=" تاریخ ایجاد",
                    ),
                ),
                (
                    "updated_time",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        null=True,
                        verbose_name="تاریخ به روز رسانی",
                    ),
                ),
                ("slug", models.SlugField(null=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="questions.category",
                        verbose_name="دسته بندی ها",
                    ),
                ),
            ],
            options={
                "verbose_name": "دسته بندی",
                "verbose_name_plural": "دسته بندیها",
                "db_table": "Category",
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_title",
                    models.CharField(
                        max_length=200, null=True, verbose_name="عنوان سوال"
                    ),
                ),
                ("slug", models.SlugField(null=True)),
                ("question_text", models.TextField(null=True, verbose_name="متن سوال")),
                (
                    "created_time",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        null=True,
                        verbose_name=" تاریخ ایجاد",
                    ),
                ),
                (
                    "updated_time",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        null=True,
                        verbose_name="تاریخ به روز رسانی",
                    ),
                ),
                (
                    "question_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="question/%Y/%m/%d",
                        verbose_name="تصویر سوال",
                    ),
                ),
                (
                    "question_category",
                    models.ManyToManyField(
                        to="questions.Category", verbose_name="دسته بندی سوال"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="سوال کننده",
                    ),
                ),
            ],
            options={
                "verbose_name": "سوال",
                "verbose_name_plural": "سوال ها",
                "db_table": "Questions",
            },
        ),
    ]
