# Generated by Django 3.1 on 2020-12-08 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("questions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer", models.TextField(null=True, verbose_name="پاسخ")),
                ("created_time", models.DateTimeField(auto_now=True, null=True)),
                ("updated_time", models.DateTimeField(auto_now=True, null=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="questions.question",
                        verbose_name="سوال",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="پاسخ دهنده",
                    ),
                ),
            ],
            options={
                "verbose_name": "پاسخ",
                "verbose_name_plural": "پاسخ ها",
                "db_table": "Answers",
            },
        ),
    ]
