# Generated by Django 3.1 on 2020-12-15 09:20

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note_title", models.CharField(max_length=40, verbose_name="عنوان")),
                ("slug", models.SlugField(null=True, verbose_name="")),
                ("note_body", ckeditor.fields.RichTextField(verbose_name="متن")),
                (
                    "note_status",
                    models.CharField(
                        choices=[("draft", "پیش نویس"), ("publish", "انتشار")],
                        max_length=8,
                        null=True,
                        verbose_name="وضعیت ",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "date_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ به روز رسانی"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="نویسنده",
                    ),
                ),
            ],
            options={
                "verbose_name": "یادداشت",
                "verbose_name_plural": "یادداشت ها",
                "db_table": "note",
            },
        ),
    ]
