# Generated by Django 3.1 on 2020-12-15 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="slug",
            field=models.SlugField(allow_unicode=True, null=True, verbose_name=""),
        ),
    ]
